### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by c9s** [freehaha/go-r3#1]
Hi!

Glad to see this binding package! 

To enhance the API simplicity, would you mind adding some helper functions to the mux?

for example,

``` go
r.Get("/", func(w http.ResponseWriter, req *http.Request) { ... });
```

Instead of:

``` go
r.HandleFunc(r3.MethodGet, "/", func(w http.ResponseWriter, req *http.Request);
```

Which I think can help the development. what do you think?

**Comment by freehaha** [comment]
sure! any pull requests are welcomed =)

**Comment by freehaha** [comment]
Hi,
I just added some helper functions. Let me know if you think there are more to add.

**Comment by c9s** [comment]
Wow! you're so fast! thanks!
